apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgergw-userdev
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-ledgergw-userdev
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-ledgergw-userdev	
    spec:
      initContainers:
          - name: file-permission-container
            image: ghcr.io/dbca-wa/docker-apps-dev:busybox_base_latest
            command: ["sh", "-c", "mkdir -p /mnt/storage/data; mkdir -p /mnt/storage/container; mkdir -p /app/logs ; chown -R 5000:5000 /mnt/storage/; "]              
            volumeMounts:
              - name: ledgergw-userdev
                mountPath: /mnt/storage/
            securityContext:
              runAsUser: 0 # Run as root user
              allowPrivilegeEscalation: true
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot                   
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot              
      containers:
        - env:
          envFrom:
            - secretRef:
                name: {{system}}-{{namespace}}-userdev
                optional: false                  
          name: ledgergw-userdev
          image: ghcr.io/dbca-wa/docker_app_dev:ledger_dev_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcp8080
              protocol: TCP
            - containerPort: 9021
              name: tcp9021
              protocol: TCP              
          stdin: true          
          tty: true     
          volumeMounts:
            - mountPath: /data/
              name: ledgergw-userdev
              subPath: data                  
            - mountPath: /home/container/
              name: ledgergw-userdev
              subPath: container   
            - mountPath: /app/.vscode-server/
              name: ledgergw-userdev
              subPath: vscode-server                 
          workingDir: /app
          resources:
            limits:
              cpu: '2'
              memory: 5Gi
            requests:
              cpu: 10m
              memory: 1Gi          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL          
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true          
            runAsUser: 5000 
      volumes:
        - name:  ledgergw-userdev
          persistentVolumeClaim:
            claimName: ledgergw-userdev

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{namespace}}8080-ledger-userdev-appsteam.dbca.wa.gov.au
  namespace: {{namespace}}
  annotations:
    # Optional: specifically for NGINX Ingress Controller
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{namespace}}8080-ledger-userdev-appsteam.dbca.wa.gov.au
    http:
      paths:
      - backend:
          service:
            name: ledgergw-userdev
            port:
              number: 8080
        pathType: ImplementationSpecific

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{namespace}}9021-ledger-userdev-appsteam.dbca.wa.gov.au
  namespace: {{namespace}}
  annotations:
    # Optional: specifically for NGINX Ingress Controller
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{namespace}}9021-ledger-userdev-appsteam.dbca.wa.gov.au
    http:
      paths:
      - backend:
          service:
            name: ledgergw-userdev
            port:
              number: 9021
        pathType: ImplementationSpecific        
            
