apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{system}}-userdev
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-appmonitor-userdev
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-appmonitor-userdev
    spec:
      initContainers:
          - name: file-permission-container
            image: busybox
            command: ["sh", "-c", "mkdir -p /opt/geoserver_data; mkdir -p /data ; mkdir -p /container/; mkdir -p /container/logs; chown -R 5000:5000 /container/logs; chown -R 5000:5000 /opt/geoserver_data; chown -R 5000:5000 /data"]              
            volumeMounts:
              - name: {{system}}-userdev
                mountPath: /mnt/storage/
            securityContext:
              runAsUser: 0 # Run as root user
              allowPrivilegeEscalation: true  
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot                   
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot                   
      containers:
        - env:
            - name: DEBUG
              value: 'True'
            - name: ENABLE_WEB
              value: 'False'
            - name: ENABLE_CRON
              value: 'False'
          envFrom:
            - secretRef:
                name: {{system}}-{{namespace}}-userdev
                optional: false                   
          name: geoserver-2-25-userdev
          image: dbcawa/appsteam-geoserver:2025.10.03.08.2949_ver2.25
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcp8080
              protocol: TCP
          stdin: true          
          tty: true     
          volumeMounts:
            - mountPath: /data/
              name: {{system}}-userdev
              subPath: data                  
            - mountPath: /opt/geoserver_data
              name: {{system}}-userdev
              subPath: geoserver_data  
            - mountPath: /container/logs
              name: {{system}}-userdev
              subPath: logs                
          workingDir: /opt/geoserver_data
          resources:
            limits:
              cpu: '1'
              memory:6Gi
            requests:
              cpu: 10m
              memory: 2Gi          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL          
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 5000
      volumes:
        - name:  geoserver-2-25-userdev
          persistentVolumeClaim:
            claimName: geoserver-2-25-userdev
            
