apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{system}}-userdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: managed-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thermal-image-share-userdev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi 
  storageClassName: azurefile-csi-retain
