apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu2404-userdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi  
  storageClassName: managed-csi
