apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{system}}-userdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi 
  storageClassName: managed-csi
